/* Framework-free interactions for direct-file hosting. */
(()=>{const $=s=>document.querySelector(s),feed=$('#feed'),input=$('#prompt'),form=$('#form'),status=$('#status'),orch=$('#orch'),drawer=$('#drawer'),scrim=$('#scrim'),open=$('#openDrawer'),close=$('#closeDrawer'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let busy=false;const data=[['CLAUDE','violet','Vanta is a reasoning relay: one prompt is framed, several specialists reason in parallel, and the shared signal comes back distilled.','1.18s','95'],['CHATGPT','cyan','Think of it as a panel of experts with one editor. Every model explores an angle while orchestration keeps the final answer coherent.','1.44s','92'],['GEMINI','blue','Vanta compares model outputs and gives you the overlap plus useful disagreement—not a noisy transcript.','1.29s','90'],['DEEPSEEK','green','The system parallelizes inference, checks consensus, and remembers only the context you choose to keep.','1.02s','93'],['PERPLEXITY','amber','For research-heavy questions, Vanta enriches the swarm with RAG memory and surfaces a grounded synthesis.','1.76s','89']];
const now=()=>new Intl.DateTimeFormat([],{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date());
function setStatus(text,color='cyan'){status.querySelector('span').textContent=text;status.querySelector('i').className=color}
function bottom(){requestAnimationFrame(()=>scrollTo({top:document.body.scrollHeight,behavior:reduced?'auto':'smooth'}))}
function user(text){const x=document.createElement('article');x.className='msg user';x.innerHTML='<div class="meta"><strong>AG</strong><span>YOU</span><time></time></div><div class="bubble"></div>';x.querySelector('time').textContent=now();x.querySelector('.bubble').textContent=text;feed.append(x)}
function card(d,i){const x=document.createElement('div');x.className='card';x.style.animationDelay=reduced?'0ms':`${i*90}ms`;x.innerHTML=`<header><b><i class="${d[1]}"></i>${d[0]}</b><small>${d[3]}</small></header><p></p><footer>${d[4]}% signal <em><i style="width:${d[4]}%"></i></em></footer>`;x.querySelector('p').textContent=d[2];return x}
function loading(){const x=document.createElement('article');x.className='msg bot';x.innerHTML='<div class="meta"><strong>V</strong><span>VANTA</span><time>ROUTING NOW</time></div><div class="stack"><div class="card is-loading"><header><b><i class="cyan"></i>ORCHESTRATOR</b><small></small></header><p></p><footer>•••</footer></div></div>';x.querySelector('small').textContent=orch.checked?'5 destinations':'single model';x.querySelector('p').textContent=orch.checked?'Framing prompt and routing to the swarm…':'Framing prompt and preparing response…';feed.append(x);return x}
function answer(){const x=document.createElement('article');x.className='msg bot';x.innerHTML='<div class="meta"><strong>V</strong><span>VANTA</span><time></time></div><div class="stack compare"></div>';x.querySelector('time').textContent=now()+' · merged response';const stack=x.querySelector('.stack');data.forEach((d,i)=>stack.append(card(d,i)));const d=document.createElement('div');d.className='divider';d.innerHTML='<span>MERGED SUMMARY · 5/5 AGREEMENT</span>';stack.append(d);const s=document.createElement('div');s.className='summary';s.innerHTML='<b>✦</b><p><strong>The Vanta read:</strong> multiple perspectives are useful when routing stays invisible, context stays grounded, and the final signal stays yours.</p>';stack.append(s);const ins=document.createElement('div');ins.className='insights';ins.innerHTML='<span class="chip">RAG · workspace context</span><span class="watch"><i></i>Watcher: consensus detected</span>';stack.append(ins);feed.append(x)}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(busy||!text)return;busy=true;user(text);input.value='';input.style.height='auto';setStatus(orch.checked?'ROUTING TO SWARM':'PROCESSING','violet');const wait=orch.checked?(reduced?350:1350):(reduced?300:850),load=loading();bottom();setTimeout(()=>{load.remove();answer();busy=false;setStatus('SYNTHESIS READY','green');bottom();setTimeout(()=>setStatus('READY TO ROUTE'),2600)},wait)});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,100)+'px'});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});document.querySelectorAll('.selectors button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.selectors button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
function toggleDrawer(force){const yes=force??!drawer.classList.contains('open');drawer.classList.toggle('open',yes);scrim.classList.toggle('open',yes);drawer.setAttribute('aria-hidden',String(!yes));open.setAttribute('aria-expanded',String(yes));if(yes)close.focus();else open.focus()}open.addEventListener('click',()=>toggleDrawer(true));close.addEventListener('click',()=>toggleDrawer(false));scrim.addEventListener('click',()=>toggleDrawer(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')toggleDrawer(false);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#clear').click()}});$('#clear').addEventListener('click',()=>{feed.innerHTML='';setStatus('SESSION CLEARED','amber');setTimeout(()=>setStatus('READY TO ROUTE'),1600)});})();